apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb-database.fullname" . }}
type: Opaque
stringData:
  username: {{ include "mariadb-database.userName" . }}
  password: {{ .Values.auth.password }}
  host: {{ include "mariadb-database.host" . }}
  port: {{ .Values.cluster.port | quote }}
  database: {{ include "mariadb-database.dbName" . }}
