{{- if .Values.discovery.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "discoverable-{{ include "mariadb-op.fullname" . }}"
  annotations:
    onyxia/discovery: "mariadb"
type: Opaque
data:
  mariadb-service: {{ include "mariadb-op.fullname" . | b64enc | quote }}
  mariadb-username: {{ .Values.auth.username | b64enc | quote }}
  mariadb-password: {{ .Values.auth.password | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
  mariadb-database: {{ .Values.auth.database | b64enc | quote }}
  mariadb-port: {{ .Values.port | toString | b64enc | quote }}
{{- end -}}
