apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb-op.fullname" . }}
type: Opaque
stringData:
  username: {{ .Values.auth.username }}
  password: {{ .Values.auth.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb-op.fullname" . }}-root
type: kubernetes.io/basic-auth
data:
  username: cm9vdA==
  password: {{ .Values.auth.password | b64enc | quote }}
